

#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Default is Emacs key bindnig
bindkey -e

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

autoload -U +X bashcompinit && bashcompinit
eval "$(stack --bash-completion-script stack)"

source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/objectx/.sdkman"
[[ -s "/Users/objectx/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/objectx/.sdkman/bin/sdkman-init.sh"
